# Generated by Django 4.0.3 on 2022-05-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_images_chemin'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='dateAno',
            field=models.DateField(auto_now=True),
        ),
    ]
