# Generated by Django 4.0.3 on 2022-05-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_anomaly_dateano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='dateAno',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
