# Generated by Django 4.0.3 on 2022-05-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_jsonnn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jsonnn',
        ),
    ]
